# Etapa de construcción
FROM node:18-alpine AS build
WORKDIR /app

# Definir y exportar variables de entorno
ARG VITE_API_LOGIN
ARG VITE_API_LOGOUT
ARG VITE_API_FORGOT_PASSWORD
ARG VITE_API_RESET_PASSWORD
ARG VITE_API_REGISTER
ARG VITE_API_DELETE_PROFILE
ARG VITE_API_UPDATE_PROFILE
ARG VITE_API_FETCH_PROFILE
ARG VITE_API_CHATBOT
ARG VITE_API_MAPGENERATOR
ARG VITE_API_GET_PRODUCTS
ARG VITE_API_GET_PRODUCTS_BY_ID
ARG VITE_API_GET_CATEGORY
ARG VITE_API_GET_CATEGORY_BY_ID
ARG VITE_API_GET_USER_BY_ID
ARG VITE_API_CREATE_PRODUCT
ARG VITE_API_SOCKET
ARG VITE_API_FETCH_CHATS
ARG VITE_API_START_CHAT
ARG VITE_API_FETCH_MESSAGES

# Convertir ARGs a ENVs para que puedan ser sobrescritos
ENV \
  VITE_API_LOGIN=${VITE_API_LOGIN} \
  VITE_API_LOGOUT=${VITE_API_LOGOUT} \
  VITE_API_FORGOT_PASSWORD=${VITE_API_FORGOT_PASSWORD} \
  VITE_API_RESET_PASSWORD=${VITE_API_RESET_PASSWORD} \
  VITE_API_REGISTER=${VITE_API_REGISTER} \
  VITE_API_DELETE_PROFILE=${VITE_API_DELETE_PROFILE} \
  VITE_API_UPDATE_PROFILE=${VITE_API_UPDATE_PROFILE} \
  VITE_API_FETCH_PROFILE=${VITE_API_FETCH_PROFILE} \
  VITE_API_CHATBOT=${VITE_API_CHATBOT} \
  VITE_API_MAPGENERATOR=${VITE_API_MAPGENERATOR} \
  VITE_API_GET_PRODUCTS=${VITE_API_GET_PRODUCTS} \
  VITE_API_GET_PRODUCTS_BY_ID=${VITE_API_GET_PRODUCTS_BY_ID} \
  VITE_API_GET_CATEGORY=${VITE_API_GET_CATEGORY} \
  VITE_API_GET_CATEGORY_BY_ID=${VITE_API_GET_CATEGORY_BY_ID} \
  VITE_API_GET_USER_BY_ID=${VITE_API_GET_USER_BY_ID} \
  VITE_API_CREATE_PRODUCT=${VITE_API_CREATE_PRODUCT} \
  VITE_API_SOCKET=${VITE_API_SOCKET} \
  VITE_API_FETCH_CHATS=${VITE_API_FETCH_CHATS} \
  VITE_API_START_CHAT=${VITE_API_START_CHAT} \
  VITE_API_FETCH_MESSAGES=${VITE_API_FETCH_MESSAGES}

# Copiar archivos y construir la aplicación
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Etapa de producción
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
